### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by royalterra** [Open-UDC/lud#2]
Hi I like to add something like that to a open source social network. I see this project not have update now for more of 2 years. Is active?

**Comment by c-geek** [comment]
I don't think so, maybe LTP (Long Time Paused).

**Comment by jbar** [comment]
Le Tue, 22 Nov 2016 10:12:08 -0800,
Cédric Moreau <notifications@github.com> a écrit :

> I don't think so, maybe LTP (Long Time Paused).
> 

the first Open-UDC client, lud, may be considered as dead.

But thttpgpd/ludd (with 2 'd') which are also fast and tiny http
servers which support some OpenPGP extensions over HTTP, are still
alive.

NB: Even if they are not a lot of commit per years, I still use my
thttpgpgd on some servers, and sometime minor bugs are discovered.

I also still want to implement the planned features (and also those
not specified in docs/*.txt but only in my mind) to make thttpgpd
servers able to efficiently works as a uncentralized pool, to manage
private datas or cryptocurrencies.

I just miss motivation (I now have a family) and time (or money to
leave my current job).




-- 
Jean-Jacques BRUCKER
